default: &default
  adapter: postgresql
  encoding: unicode
  #host: localhost
  host: <%= ENV["POSTGRES_HOST"] %> #<--the name of the db in the docker-compose
  pool: 5
  port: 5432
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development: &development
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE_NAME"] %>

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: consul_test
