default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_interceptor_recipients: <%= ENV["EMAIL_INTERCEPTOR_RECIPIENTS"] %>

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  microsoft_api_key: <%= ENV["MICROSOFT_API_KEY"] %>
  census_api_end_point: <%= ENV["CENSUS_API_END_POINT"] %>
  census_api_institution_code: <%= ENV["CENSUS_API_INSTITUTION_CODE"] %>
  census_api_portal_name: <%= ENV["CENSUS_API_PORTAL_NAME"] %>
  census_api_user_code: <%= ENV["CENSUS_API_USER_CODE"] %>
  sms_end_point:  <%= ENV["SMS_END_POINT"] %>
  sms_username: <%= ENV["SMS_USERNAME"] %>
  sms_password: <%= ENV["SMS_PASSWORD"] %>

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: <%= ENV["HTTP_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"] %>
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>
  server_name: <%= ENV["STAGING_SERVER_NAME"] %>
  rollbar_server_token: <%= ENV["STAGING_ROLLBAR_SERVER_TOKEN"] %>
  http_basic_username: <%= ENV["STAGING_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["STAGING_BASIC_PASSWORD"] %>
  managers_url: <%= ENV["STAGING_MANAGERS_URL"] %>
  managers_application_key: <%= ENV["STAGING_MANAGERS_APPLICATION_KEY"] %>"
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  secret_key_base: <%= ENV["PREPRODUCTION_SECRET_KEY_BASE"] %>
  server_name: <%= ENV["PREPRODUCTION_SERVER_NAME"] %>
  rollbar_server_token: <%= ENV["PREPRODUCTION_ROLLBAR_SERVER_TOKEN"] %>
  http_basic_username: <%= ENV["PREPRODUCTION_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["PREPRODUCTION_BASIC_PASSWORD"] %>
  managers_url: <%= ENV["PREPRODUCTION_MANAGERS_URL"] %>
  managers_application_key: <%= ENV["PREPRODUCTION_MANAGERS_APPLICATION_KEY"] %>
  twitter_key: <%= ENV["PREPRODUCTION_TWITTER_KEY"] %>
  twitter_secret: <%= ENV["PREPRODUCTION_TWITTER_SECRET"] %>
  facebook_key: <%= ENV["PREPRODUCTION_FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["PREPRODUCTION_FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["PREPRODUCTION_GOOGLE_OAUTH2_KEY"] %>
  google_oauth2_secret: <%= ENV["PREPRODUCTION_GOOGLE_OAUTH2_SECRET"] %>
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
  server_name: <%= ENV["PRODUCTION_SERVER_NAME"] %>
  rollbar_server_token: <%= ENV["PRODUCTION_ROLLBAR_SERVER_TOKEN"] %>
  http_basic_username: <%= ENV["PRODUCTION_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["PPRODUCTION_BASIC_PASSWORD"] %>
  managers_url: <%= ENV["PRODUCTION_MANAGERS_URL"] %>
  managers_application_key: <%= ENV["PRODUCTION_MANAGERS_APPLICATION_KEY"] %>
  twitter_key: <%= ENV["PRODUCTION_TWITTER_KEY"] %>
  twitter_secret: <%= ENV["PRODUCTION_TWITTER_SECRET"] %>
  facebook_key: <%= ENV["PRODUCTION_FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["PRODUCTION_FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["PRODUCTION_GOOGLE_OAUTH2_KEY"] %>
  google_oauth2_secret: <%= ENV["PRODUCTION_GOOGLE_OAUTH2_SECRET"] %>
  <<: *maps
  <<: *apis
